FROM swift:6.0.3
RUN swift sdk install "https://github.com/finagolfin/swift-android-sdk/releases/download/6.0.3/swift-6.0.3-RELEASE-android-24-0.1.artifactbundle.tar.gz" --checksum "4566f23ae2d36dc5c02e915cd67d83b2af971faca4b2595fdd75cf0286acfac1"
