FROM swift:6.0.3
RUN swift sdk install "https://download.swift.org/swift-6.0.3-release/static-sdk/swift-6.0.3-RELEASE/swift-6.0.3-RELEASE_static-linux-0.0.1.artifactbundle.tar.gz" --checksum "67f765e0030e661a7450f7e4877cfe008db4f57f177d5a08a6e26fd661cdd0bd"
