name: Build 5 random packages

on:
  workflow_dispatch:

jobs:
  get-next-packages:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-6.1-jammy
    outputs:
      packages: ${{ steps.get-next-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Get next packages
        id: get-next-packages
        run: swift run GetNextPackages
  build-repo:
    needs: get-next-packages
    continue-on-error: true
    strategy:
      matrix:
        repo: ${{ fromJSON(needs.get-next-packages.outputs.packages) }}
        sdk: [wasm, musl, android, windows]
        include:
          - sdk: wasm
            os: ubuntu-latest
            container: docker://ghcr.io/ph1ps/swift-wasm:latest
            build: swift build --swift-sdk 6.0.3-RELEASE-wasm32-unknown-wasi
          - sdk: musl
            os: ubuntu-latest
            container: docker://ghcr.io/ph1ps/swift-musl:latest
            build: swift build --swift-sdk swift-6.0.3-RELEASE_static-linux-0.0.1
          - sdk: android
            os: ubuntu-latest
            container: docker://ghcr.io/ph1ps/swift-android:latest
            build: swift build --swift-sdk swift-6.0.3-RELEASE-android-24-0.1
          - sdk: windows
            os: windows-latest
            build: swift build
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: compnerd/gha-setup-swift@main
        if: matrix.os == windows-latest
        with:
          branch: swift-6.0.3-release
          tag: 6.0.3-RELEASE
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          fetch-depth: 1
      - name: Build
        run: ${{ matrix.build }}
