name: Build random packages

on:
  workflow_dispatch:

jobs:
  get-next-packages:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-6.1-jammy
    outputs:
      packages: ${{ steps.get-next-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Get next packages
        id: get-next-packages
        run: swift run GetNextPackages
      - uses: actions/upload-artifact@v4
        with:
          name: selected-packages
          path: selected-packages.json
  build-repo:
    needs: get-next-packages
    continue-on-error: true
    strategy:
      matrix:
        sdk: [wasm, musl, android, windows]
        include:
          - sdk: wasm
            os: ubuntu-latest
            container: docker://ghcr.io/ph1ps/swift-wasm:latest
            build: SWIFT_SDK=6.0.3-RELEASE-wasm32-unknown-wasi swift run BuildPackage
          - sdk: musl
            os: ubuntu-latest
            container: docker://ghcr.io/ph1ps/swift-musl:latest
            build: SWIFT_SDK=swift-6.0.3-RELEASE_static-linux-0.0.1 swift run BuildPackage
          - sdk: android
            os: ubuntu-latest
            container: docker://ghcr.io/ph1ps/swift-android:latest
            build: SWIFT_SDK=swift-6.0.3-RELEASE-android-24-0.1 swift run BuildPackage
          - sdk: windows
            os: windows-latest
            build: swift build
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    steps:
      - uses: compnerd/gha-setup-swift@main
        if: matrix.os == 'windows-latest'
        with:
          branch: swift-6.0.3-release
          tag: 6.0.3-RELEASE
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            .build
            .swiftpm
          key: ${{ hashFiles('**/Packages.resolved') }}
      - uses: actions/download-artifact@v4
        with:
          name: selected-packages
          path: selected-packages.json
      - name: Build
        run: ${{ matrix.build }}
