name: build

on:
  workflow_dispatch:

jobs:
  get-next-packages:
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-6.1-jammy
    outputs:
      packages: ${{ steps.get-next-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Get next packages
        id: get-next-packages
        run: swift run GetNextPackages
  build-repo:
    needs: get-next-packages
    strategy:
      matrix:
        repo: ${{ fromJSON(needs.get-next-packages.outputs.packages) }}
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            container_image: swift:6.0.3
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container_image }}
    steps:
      - uses: compnerd/gha-setup-swift@main
        if: matrix.os == 'windows-latest'
        with:
          branch: swift-6.0.3-release
          tag: 6.0.3-RELEASE
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repo }}
          fetch-depth: 1
      - name: Build
        run: swift build
