name: build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    #runs-on: ubuntu-latest
    #container: swift:6.0.3
    steps:
      - uses: actions/checkout@v4
      - name: Run script
        run: swift run
